#!/bin/bash
# skill-capture.sh — Scaffold a new skill from a learned pipeline
#
# Usage:
#   scripts/skill-capture.sh NAME "DESCRIPTION" "COMMAND" [--relay-home PATH] [--force]
#
# Example:
#   scripts/skill-capture.sh tts-macos "macOS TTS fallback" "say '\$1' -o /tmp/out.aiff"

set -e

# ── Parse arguments ──────────────────────────────────────────────────

NAME=""
DESCRIPTION=""
COMMAND=""
RELAY_HOME="${RELAY_HOME:-$HOME/relay}"
FORCE=0

positional=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --relay-home) RELAY_HOME="$2"; shift 2 ;;
        --force)      FORCE=1; shift ;;
        --help|-h)
            echo "Usage: skill-capture.sh NAME \"DESCRIPTION\" \"COMMAND\" [--relay-home PATH] [--force]"
            echo ""
            echo "  NAME          Skill slug (lowercase, kebab-case)"
            echo "  DESCRIPTION   One-line description"
            echo "  COMMAND       The pipeline or command to save"
            echo "  --relay-home  Agent workspace (default: ~/relay)"
            echo "  --force       Overwrite existing skill"
            exit 0
            ;;
        *) positional+=("$1"); shift ;;
    esac
done

NAME="${positional[0]:?Usage: skill-capture.sh NAME \"DESCRIPTION\" \"COMMAND\"}"
DESCRIPTION="${positional[1]:?Usage: skill-capture.sh NAME \"DESCRIPTION\" \"COMMAND\"}"
COMMAND="${positional[2]:?Usage: skill-capture.sh NAME \"DESCRIPTION\" \"COMMAND\"}"

# Sanitize name
NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')

SKILL_DIR="$RELAY_HOME/skills/$NAME"
TODAY=$(date +%Y-%m-%d)

# ── Check for existing skill ────────────────────────────────────────

if [ -d "$SKILL_DIR" ] && [ "$FORCE" -eq 0 ]; then
    echo "Error: Skill '$NAME' already exists at $SKILL_DIR"
    echo "Use --force to overwrite."
    exit 1
fi

# ── Create skill directory ──────────────────────────────────────────

mkdir -p "$SKILL_DIR"

# ── Write SKILL.md ──────────────────────────────────────────────────

cat > "$SKILL_DIR/SKILL.md" << SKILL_EOF
---
name: $NAME
description: $DESCRIPTION
entry_point: ~/relay/skills/$NAME/run.sh
requires: []
triggers: []
captured_from: $TODAY
---

# $NAME

$DESCRIPTION

Captured on $TODAY from a working session pipeline.

## Usage

\`\`\`bash
~/relay/skills/$NAME/run.sh [args]
\`\`\`

## Pipeline

\`\`\`bash
$COMMAND
\`\`\`
SKILL_EOF

# ── Write run.sh ────────────────────────────────────────────────────

cat > "$SKILL_DIR/run.sh" << 'RUN_HEADER'
#!/bin/bash
# Auto-generated by skill-capture.sh
set -e
RUN_HEADER

echo "$COMMAND" >> "$SKILL_DIR/run.sh"
chmod +x "$SKILL_DIR/run.sh"

# ── Report ──────────────────────────────────────────────────────────

echo "Skill captured: $NAME"
echo ""
echo "  $SKILL_DIR/"
echo "  ├── SKILL.md    ← Metadata (edit requires/triggers)"
echo "  └── run.sh      ← Pipeline"
echo ""
echo "Next: edit SKILL.md to add requires and triggers, then run:"
echo "  scripts/skill-manifest.sh $RELAY_HOME"
