#!/bin/bash
# skill-manifest.sh — Scan skill directories, check dependencies, output SKILLS.md
#
# Usage:
#   scripts/skill-manifest.sh RELAY_HOME [OUTPUT_PATH]
#
# RELAY_HOME: agent workspace (contains skills/ and config/relay.conf)
# OUTPUT_PATH: where to write SKILLS.md (default: $RELAY_HOME/SKILLS.md)

set -e

RELAY_HOME="${1:?Usage: skill-manifest.sh RELAY_HOME [OUTPUT_PATH]}"
OUTPUT="${2:-$RELAY_HOME/SKILLS.md}"
CONF="$RELAY_HOME/config/relay.conf"

# ── Helpers ──────────────────────────────────────────────────────────

# Read a simple key: value from YAML frontmatter (between --- delimiters)
# Usage: fm_get "field_name" < file
fm_get() {
    awk -v key="$1" '
        /^---$/ { block++; next }
        block == 1 && $0 ~ "^"key":" {
            sub("^"key":[ ]*", "")
            gsub(/"/, "")
            print
            exit
        }
    '
}

# Read a YAML list from frontmatter (  - item lines under a key)
# Usage: fm_list "field_name" file
fm_list() {
    awk -v key="$1" '
        /^---$/ { block++; next }
        block == 1 && $0 ~ "^"key":" { capture=1; next }
        block == 1 && capture && /^  - / {
            val = $0
            sub("^  - ", "", val)
            gsub(/"/, "", val)
            print val
            next
        }
        block == 1 && capture && !/^  - / { capture=0 }
        block >= 2 { exit }
    ' "$2"
}

# Check if a config key exists and is non-empty in relay.conf
config_has() {
    local key="$1"
    [ -f "$CONF" ] || return 1
    local val
    val=$(grep "^${key}[[:space:]]*=" "$CONF" 2>/dev/null | head -1 | cut -d= -f2- | tr -d ' ')
    [ -n "$val" ] && [ "$val" != "YOUR_"* ]
}

# Check if a binary is in PATH
bin_has() {
    command -v "$1" >/dev/null 2>&1
}

# ── Scan skills directory ────────────────────────────────────────────

SKILLS_DIR="$RELAY_HOME/skills"
if [ ! -d "$SKILLS_DIR" ]; then
    echo "# Skills & Tools" > "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "No skills directory found." >> "$OUTPUT"
    exit 0
fi

# Collect skill data
declare -a ROWS=()

# Scan both root .md files and subdirectory SKILL.md files
skill_files=()
for f in "$SKILLS_DIR"/*.md; do [ -f "$f" ] && skill_files+=("$f"); done
for f in "$SKILLS_DIR"/*/SKILL.md; do [ -f "$f" ] && skill_files+=("$f"); done

for skill_file in "${skill_files[@]}"; do
    # Check if file has YAML frontmatter
    head -1 "$skill_file" | grep -q "^---$" || continue

    name=$(fm_get "name" < "$skill_file")
    [ -z "$name" ] && continue

    description=$(fm_get "description" < "$skill_file")
    entry_point=$(fm_get "entry_point" < "$skill_file")
    fallback=$(fm_get "fallback" < "$skill_file")

    # Read triggers
    triggers=""
    while IFS= read -r t; do
        [ -z "$t" ] && continue
        if [ -z "$triggers" ]; then
            triggers="$t"
        else
            triggers="$triggers, $t"
        fi
    done < <(fm_list "triggers" "$skill_file")

    # Check dependencies
    status="ok"
    missing=""

    while IFS= read -r dep; do
        [ -z "$dep" ] && continue
        dep_type="${dep%%:*}"
        dep_name="${dep#*:}"

        case "$dep_type" in
            config)
                if ! config_has "$dep_name"; then
                    if [ -z "$missing" ]; then
                        missing="config:$dep_name"
                    else
                        missing="$missing, config:$dep_name"
                    fi
                    status="degraded"
                fi
                ;;
            bin)
                if ! bin_has "$dep_name"; then
                    if [ -z "$missing" ]; then
                        missing="bin:$dep_name"
                    else
                        missing="$missing, bin:$dep_name"
                    fi
                    status="unavailable"
                fi
                ;;
        esac
    done < <(fm_list "requires" "$skill_file")

    # Build status string
    status_str="$status"
    if [ "$status" != "ok" ] && [ -n "$missing" ]; then
        status_str="$status — missing $missing"
        if [ -n "$fallback" ]; then
            status_str="$status_str — fallback: $fallback"
        fi
    fi

    ROWS+=("| $name | $status_str | $triggers | \`$entry_point\` | $description |")
done

# ── Write SKILLS.md ──────────────────────────────────────────────────

{
    echo "# Skills & Tools"
    echo ""
    echo "Auto-generated by skill-manifest.sh. For full documentation, read the skill file directly (e.g. \`cat ~/relay/skills/speak.md\`)."
    echo ""
    echo "| Skill | Status | Triggers | Path | Description |"
    echo "|-------|--------|----------|------|-------------|"
    for row in "${ROWS[@]}"; do
        echo "$row"
    done
} > "$OUTPUT"

echo "SKILLS.md written: $OUTPUT (${#ROWS[@]} skills)"
